### PR TITLE
Numerous fixes for adaptor.js

### PR DESCRIPTION
**Pull request by foxel**
Array fields for models
Model enum fields
Operation responses split to errors and successes
Complex types improved

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Are all these changes to match behaviour in `swagger-codegen` or are any of them extensions?

**Comment by foxel** [comment]
model.hasComplex and Operation responses split  are extensions

**Comment by MikeRalphson** [comment]
Could we move the extensions under an `openapi` property of the respective objects, e.g. `model.openapi.hasComplex` and add them to `docs/modelProperties.md` ?

Sorry to be a pain.

**Comment by MikeRalphson** [comment]
I guess you're working on https://github.com/foxel/openapi3-typescript-codegen now, so unless you still feel inclined to split this PR up, we'd probably best close it.

**Pull request closed without merging**
