### PR TITLE
Getting typescript-angular work

### PR DESCRIPTION
**Pull request by foxel**
Getting typescript-angular work.

What's done besides templates being modified:
* distinguish different 'HTTP' auth schemes (basic vs bearer for now)
* $ref for operation body
* distinguish error responses from success
* fixed schemas with more than one enum field
* output directory command line argument

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Many thanks for the PR!

Could you let me know if the changes to the templates are due to deficiencies in the templates themselves, or to work around bugs or incompatibilities between swagger-codegen and our adaptor/model?

It might be nice to split this into two PRs, one which touches the templates and one which does not, and maybe eliminate some whitespace changes (like the omitting of blank lines at the end of files).

Thanks again!

**Comment by foxel** [comment]
@MikeRalphson, unfortunately when I started trying this code, Angular integration didn't work at all. So most of the work is to make ends meet from both sides: templates and code. The only change that is kinda separate is adding output folder option.

**Comment by MikeRalphson** [comment]
Perhaps we could move the modified templates to a new directory structure, such as

`/templates/clients/javascript/angular`

This would also help provide a basis for `openapi-codegen` as a web API / service.

What I'm trying to say is that `openapi-codegen` is designed to work with unmodified upstream templates, so the ideal case would be to add all the model/adaptor code improvements here, but template improvements to `swagger-codegen`.

I appreciate that may not be possible or easy, especially as `swagger-codegen` is in the midst of its upgrade to OAS 3 support.

Thoughts?

**Comment by foxel** [comment]
Hmmm... I get your idea of using unmodified templates... In this case one should try integrate latest templates from upstream here (I might do this later if have time).

Regarding my usage of `openapi-codegen` in the project I lead... I think in this case it's better to have an option of using external config+templates for the generation.

What do you think?

**Comment by MikeRalphson** [comment]
There's a script for pulling in the latest upstream templates. I'll run and push in a short while.

**Comment by MikeRalphson** [comment]
I've updated the templates. There's a couple of test failures to address in configs `go` and `lua`, so Travis might show errors until this is fixed.

**Comment by foxel** [comment]
@MikeRalphson I've looked thru the templates from latest upstream. They are not good compatible with Open API 3. The most problematic section is POST/PUT payloads. In 2.0 (which are templates for) there are in body params, they are bodyParams in template; and in 3.0 there are requestBody sections in definition that do set whole body as a param. Also authorization definiutions of 3.0 are richer and can't be supported with templatyes we have in upstream. Pity

**Comment by MikeRalphson** [comment]
Hi, it's not clear to me whether you have looked at the upstream templates in the master branch, or the 3.0 branch (or both).

The templates in the 3.0 branch - although designed for OpenAPI 3.0 will not be a good match to our current adaptor/model.

The templates in the master branch (for swagger-codegen 2.4) should work fine - possibly with some additions to the adaptor/model.

When processing OpenAPI 3.0 we fake a body parameter from the requestBody, so this should not be a problem. Down-converting the security from OpenAPI 3.0 to 2.0-compatible does, as you say, involve some loss.

I would still like to break this PR down to see if we can accept some aspects of it, and maybe copy the amended templates into a new directory/config-name. But I can do that if you want.

**Comment by MikeRalphson** [comment]
> I think in this case it's better to have an option of using external config+templates for the generation.

Maybe this is the best plan though?

**Comment by foxel** [comment]
@MikeRalphson I've created two more separate PRs from this one.
And I agree to have CLI option to provide custom config and templates

**Comment by MikeRalphson** [comment]
Custom output and template directory options have been implemented. Thanks for splitting the PR.

**Pull request closed without merging**
